#!/usr/bin/env python3
"""
API Printer Service — Linux Installer
Runs as a Tkinter GUI wizard when a display is available, or as a
step-by-step terminal wizard when running headless / over SSH.

Supports X11 and Wayland (via XWayland).  Works on Debian 12/13 and
Ubuntu 22.04/24.04.  Must be run as root (sudo or pkexec).
"""

import os
import sys
import re
import shutil
import socket
import subprocess
import threading
import platform
from pathlib import Path
from typing import NamedTuple

BUNDLE_DIR = Path(getattr(sys, "_MEIPASS", Path(__file__).parent.parent.parent))
VERSION    = "1.0.0"
DEFAULT_INSTALL_DIR = "/opt/api-printer-service"
LOG_FILE   = "/var/log/api-printer.log"
SERVICE_BINARY_NAME = "api-printer-service-linux"
GUI_SCRIPT_NAME     = "printer_control_gui.py"
UPDATE_HELPER_NAME  = "update_notifier.py"
DESKTOP_ENTRY_NAME  = "api-printer-gui.desktop"
LAUNCHER_PATH       = "/usr/bin/api-printer-gui"
APPLICATIONS_DESKTOP_PATH = f"/usr/share/applications/{DESKTOP_ENTRY_NAME}"
AUTOSTART_DESKTOP_PATH    = f"/etc/xdg/autostart/{DESKTOP_ENTRY_NAME}"
SETTINGS_DIR = "/etc/api-printer-service"
POLKIT_RULE_PATH = "/etc/polkit-1/rules.d/50-api-printer-service.rules"

# polkit rule: let the logged-in desktop user start/stop/restart our unit
# without a password prompt, so the GUI's control buttons work silently.
# subject.active limits this to users with a local, foreground session —
# SSH connections don't qualify.
POLKIT_RULE = """\
// Generated by the API Printer Service installer — do not edit by hand.
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.systemd1.manage-units" &&
        action.lookup("unit") == "api-printer.service" &&
        subject.active) {
        return polkit.Result.YES;
    }
});
"""

SERVICE_UNIT = """\
[Unit]
Description=API Printer Service - REST API for Receipt Printing
After=network.target cups.service

[Service]
Type=simple
User=root
WorkingDirectory={install_dir}
Environment="LOG_FILE=/var/log/api-printer.log"
ExecStart={install_dir}/{service_binary}
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""


# =============================================================================
# System compatibility checks
# =============================================================================

class Check(NamedTuple):
    name: str
    status: str   # "ok" | "warn" | "fail"
    message: str = ""


def _system_glibc() -> str | None:
    """Return the running system's glibc version (e.g. '2.39')."""
    try:
        return os.confstr("CS_GNU_LIBC_VERSION").split()[-1]
    except (AttributeError, ValueError, OSError):
        return None


def _binary_required_glibc(binary_path: Path) -> str | None:
    """Scan an ELF binary for the highest GLIBC_x.y symbol version it needs."""
    try:
        data = binary_path.read_bytes()
    except OSError:
        return None
    versions = [m.decode() for m in re.findall(rb"GLIBC_(\d+\.\d+)", data)]
    if not versions:
        return None
    return max(versions, key=lambda v: tuple(int(x) for x in v.split(".")))


def _version_ge(a: str, b: str) -> bool:
    return tuple(int(x) for x in a.split(".")) >= tuple(int(x) for x in b.split("."))


def _run_system_checks() -> list[Check]:
    """
    Run pre-install compatibility checks.  Returns a list of Check tuples.
    Any Check with status="fail" blocks installation; "warn" asks the user
    to confirm; "ok" is silent-pass.
    """
    checks: list[Check] = []

    # Platform
    if sys.platform.startswith("linux"):
        checks.append(Check("Operating system", "ok", "Linux"))
    else:
        checks.append(Check("Operating system", "fail",
                            f"Requires Linux; detected {sys.platform}"))

    # CPU architecture — the embedded binary is x86_64
    arch = platform.machine()
    if arch in ("x86_64", "amd64"):
        checks.append(Check("CPU architecture", "ok", arch))
    else:
        checks.append(Check("CPU architecture", "fail",
                            f"Requires x86_64; detected {arch}"))

    # glibc — compare the system's version against what the bundled
    # service binary actually links against (read from the ELF itself).
    binary = BUNDLE_DIR / SERVICE_BINARY_NAME
    required = _binary_required_glibc(binary) if binary.exists() else None
    system = _system_glibc()
    if required and system:
        if _version_ge(system, required):
            checks.append(Check("glibc", "ok",
                                f"system {system} ≥ required {required}"))
        else:
            checks.append(Check("glibc", "fail",
                                f"need glibc ≥ {required}, system has {system} "
                                "— upgrade to Debian 13 or Ubuntu 24.04"))
    elif system:
        checks.append(Check("glibc", "warn",
                            f"system {system}; could not read required version "
                            "from embedded binary"))
    else:
        checks.append(Check("glibc", "warn",
                            "could not determine system glibc version"))

    # systemd — we write a .service unit and enable it
    if not shutil.which("systemctl"):
        checks.append(Check("systemd", "fail", "systemctl not found on PATH"))
    elif not Path("/run/systemd/system").exists():
        checks.append(Check("systemd", "fail",
                            "systemd is not the active init "
                            "(no /run/systemd/system)"))
    else:
        checks.append(Check("systemd", "ok", ""))

    # CUPS — warning only; user can install it afterwards.  The service
    # shells out to lpstat/lpr/cancel at runtime, so without CUPS it
    # starts but every print request fails.
    if shutil.which("lpstat"):
        checks.append(Check("CUPS", "ok", ""))
    else:
        checks.append(Check("CUPS", "warn",
                            "lpstat not found — install with "
                            "`apt install cups` before printing"))

    # Port 5058 — the service binds here.  If our own systemd unit is
    # holding it, we treat that as OK: the install flow stops the service
    # before overwriting the binary and restarts it at the end.  Only an
    # *unrelated* process on the port warrants a warning.
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            s.bind(("127.0.0.1", 5058))
        checks.append(Check("Port 5058", "ok", ""))
    except OSError as e:
        if _existing_service_is_active():
            checks.append(Check("Port 5058", "ok",
                                "held by existing api-printer.service "
                                "(installer will stop and restart it)"))
        else:
            checks.append(Check("Port 5058", "warn",
                                f"already in use ({e.strerror}); service will "
                                "fail to start until the port is freed"))

    return checks


def _existing_service_is_active() -> bool:
    """True if the previously-installed api-printer.service is running."""
    if not shutil.which("systemctl"):
        return False
    r = subprocess.run(
        ["systemctl", "is-active", "api-printer.service"],
        capture_output=True, text=True, env=_system_env(),
    )
    return r.stdout.strip() == "active"


def _checks_blocking(checks: list[Check]) -> list[Check]:
    return [c for c in checks if c.status == "fail"]


def _checks_warnings(checks: list[Check]) -> list[Check]:
    return [c for c in checks if c.status == "warn"]


# =============================================================================
# Display detection — handles sudo-stripped env vars + Wayland
# =============================================================================

def _restore_display_from_proc() -> None:
    """
    When the installer is invoked with ``sudo ./installer``, the kernel
    strips DISPLAY / WAYLAND_DISPLAY / XAUTHORITY / XDG_RUNTIME_DIR.
    Walk up /proc/<pid>/environ to find them in a parent process that
    still has a live graphical session.

    This is Linux-only and completely safe: we are already root, so
    /proc/<pid>/environ is readable for any PID.
    """
    needed = {"DISPLAY", "WAYLAND_DISPLAY", "XAUTHORITY", "XDG_RUNTIME_DIR"}
    # Nothing to do if we already have at least a display variable
    if os.environ.get("DISPLAY") or os.environ.get("WAYLAND_DISPLAY"):
        return

    pid = os.getppid()
    for _ in range(10):          # look at most 10 levels up the tree
        try:
            env_raw = Path(f"/proc/{pid}/environ").read_bytes()
        except OSError:
            break

        found: dict[str, str] = {}
        for entry in env_raw.split(b"\x00"):
            if b"=" in entry:
                k, _, v = entry.partition(b"=")
                try:
                    found[k.decode()] = v.decode()
                except UnicodeDecodeError:
                    pass

        for var in needed:
            if var in found and var not in os.environ:
                os.environ[var] = found[var]

        if os.environ.get("DISPLAY") or os.environ.get("WAYLAND_DISPLAY"):
            return           # found what we needed

        # Move to parent PID
        try:
            stat = Path(f"/proc/{pid}/stat").read_text()
            # Format: pid (comm) state ppid ...
            after_comm = stat.split(")", 1)[1]
            ppid = int(after_comm.split()[1])
        except (OSError, IndexError, ValueError):
            break
        if ppid <= 1:
            break
        pid = ppid


def _has_display() -> bool:
    """Return True if a graphical display is reachable by Tkinter."""
    # Attempt to recover display vars stripped by sudo
    if os.geteuid() == 0:
        _restore_display_from_proc()

    if not os.environ.get("DISPLAY") and not os.environ.get("WAYLAND_DISPLAY"):
        return False

    # Tkinter uses XWayland on Wayland sessions — a $DISPLAY is still needed.
    # If only WAYLAND_DISPLAY is set (no XWayland), Tk would fail.
    # The actual probe below catches that case.
    try:
        import tkinter as tk
        root = tk.Tk()
        root.withdraw()   # hide the test window immediately
        root.destroy()
        return True
    except Exception:
        return False


# =============================================================================
# Shared installation logic (used by both GUI and terminal modes)
# =============================================================================

def run_install_steps(install_dir: str, log_fn, progress_fn):
    """
    Execute each install step.
      log_fn(msg)              — called to append a log line
      progress_fn(pct, label)  — called to update progress (0–100)
    Raises on error.
    """
    steps = [
        (  5, "Stopping existing service",         _step_stop_existing),
        ( 15, "Creating directories",              _step_mkdir),
        ( 30, "Installing service binary",         _step_copy_service),
        ( 45, "Installing GUI",                    _step_copy_gui),
        ( 60, "Installing GUI dependencies",       _step_apt_deps),
        ( 75, "Registering desktop launcher",      _step_desktop),
        ( 85, "Granting GUI service permissions",  _step_polkit),
        ( 95, "Registering systemd service",       _step_systemd),
        (100, "Done",                              None),
    ]
    for pct, label, fn in steps:
        progress_fn(pct, label + "…")
        log_fn(f"► {label}")
        if fn:
            fn(install_dir, log_fn)
    log_fn("\n✓  Installation complete!")


def _step_stop_existing(install_dir, log):
    """
    Stop any previously-installed instance so we can overwrite its binary.

    Linux returns ETXTBSY (Errno 26, "Text file busy") on any attempt to
    open a running executable for writing, so an upgrade-install on top
    of a live service fails at the copy step without this.  Idempotent:
    succeeds silently on fresh installs where the unit does not yet exist.
    """
    env = _system_env()

    if shutil.which("systemctl"):
        # `systemctl cat` exits non-zero when the unit file is absent —
        # cheaper than parsing list-units and works before daemon-reload.
        has_unit = subprocess.run(
            ["systemctl", "cat", "api-printer.service"],
            capture_output=True, text=True, env=env,
        ).returncode == 0
        if has_unit:
            log("  systemctl stop api-printer.service")
            r = subprocess.run(
                ["systemctl", "stop", "api-printer.service"],
                capture_output=True, text=True, env=env,
            )
            for line in (r.stdout + r.stderr).splitlines():
                if line.strip():
                    log(f"    {line}")

    # Fallback: if the binary at the target path is still held by a
    # non-systemd process (manual launch, orphaned child), SIGTERM it so
    # the copy step can succeed.  fuser is part of psmisc and not always
    # installed, so we skip silently when it is missing.
    target = Path(install_dir) / SERVICE_BINARY_NAME
    if target.exists() and shutil.which("fuser"):
        subprocess.run(
            ["fuser", "-k", "-TERM", str(target)],
            capture_output=True, text=True, env=env,
        )


def _step_mkdir(install_dir, log):
    os.makedirs(install_dir, exist_ok=True)
    # Settings dir: service (as root) persists default printer here
    os.makedirs(SETTINGS_DIR, exist_ok=True)

def _step_copy_service(install_dir, log):
    # The service binary is embedded in our PyInstaller bundle via
    # --add-binary and extracted into sys._MEIPASS at startup.
    src = BUNDLE_DIR / SERVICE_BINARY_NAME
    if not src.exists():
        raise FileNotFoundError(
            f"Service binary not found in installer bundle ({src}). "
            "The installer was built incorrectly — re-run the CI "
            "build-linux step."
        )
    dst = Path(install_dir) / SERVICE_BINARY_NAME
    log(f"  copy {SERVICE_BINARY_NAME}")
    shutil.copy2(src, dst)
    dst.chmod(0o755)

def _step_copy_gui(install_dir, log):
    # GUI script is embedded as a data file in the installer bundle.
    src = BUNDLE_DIR / GUI_SCRIPT_NAME
    if not src.exists():
        raise FileNotFoundError(
            f"GUI script not found in installer bundle ({src}). "
            "The installer was built incorrectly — re-run the CI "
            "build-linux step."
        )
    dst = Path(install_dir) / GUI_SCRIPT_NAME
    log(f"  copy {GUI_SCRIPT_NAME}")
    shutil.copy2(src, dst)
    dst.chmod(0o755)

    # Update-check helper lives beside the GUI so `import update_notifier`
    # resolves from the script's own directory. Best-effort: an installer
    # built without it (older CI) still produces a working install.
    src_helper = BUNDLE_DIR / UPDATE_HELPER_NAME
    if src_helper.exists():
        dst_helper = Path(install_dir) / UPDATE_HELPER_NAME
        log(f"  copy {UPDATE_HELPER_NAME}")
        shutil.copy2(src_helper, dst_helper)
        dst_helper.chmod(0o644)
    else:
        log(f"  ({UPDATE_HELPER_NAME} not in bundle — update checks disabled)")

def _step_apt_deps(install_dir, log):
    """
    Install GTK3 + AppIndicator runtime dependencies for the GUI.
    The GUI runs under the user's session (not as root), so we install
    the distro packages rather than pip-installing PyGObject into a venv.
    """
    env = _system_env()
    env["DEBIAN_FRONTEND"] = "noninteractive"

    log("  apt-get update")
    subprocess.run(["apt-get", "update"],
                   env=env, capture_output=True, text=True, timeout=120)

    # Core — GTK3 + GObject bindings.  Fatal if missing.
    core = ["python3", "python3-gi", "gir1.2-gtk-3.0"]
    log(f"  apt-get install -y {' '.join(core)}")
    r = subprocess.run(["apt-get", "install", "-y"] + core,
                       env=env, capture_output=True, text=True, timeout=300)
    for line in (r.stdout + r.stderr).splitlines():
        if line.strip():
            log(f"    {line}")
    if r.returncode != 0:
        detail = (r.stderr or r.stdout or "").strip() \
                 or f"exit status {r.returncode}"
        raise RuntimeError(f"apt-get install failed:\n{detail}")

    # Tray indicator: prefer Ayatana, fall back to legacy.  Best-effort;
    # the window still works without a tray icon.
    for pkg in ("gir1.2-ayatanaappindicator3-0.1", "gir1.2-appindicator3-0.1"):
        log(f"  apt-get install -y {pkg}")
        r = subprocess.run(["apt-get", "install", "-y", pkg],
                           env=env, capture_output=True, text=True, timeout=180)
        if r.returncode == 0:
            break
        log(f"    (skipped: {pkg} not available)")

    # GNOME extension — only required on GNOME sessions.  Optional.
    log("  apt-get install -y gnome-shell-extension-appindicator (optional)")
    subprocess.run(
        ["apt-get", "install", "-y", "gnome-shell-extension-appindicator"],
        env=env, capture_output=True, text=True, timeout=180,
    )

    # notify-send — transport for the daily update notification (plyer's
    # Linux backend and update_notifier's fallback both use it). Optional;
    # without it the GUI only loses the desktop notification.
    log("  apt-get install -y libnotify-bin (optional, update notifications)")
    subprocess.run(
        ["apt-get", "install", "-y", "libnotify-bin"],
        env=env, capture_output=True, text=True, timeout=180,
    )

def _step_polkit(install_dir, log):
    """
    Install a polkit rule so the desktop user can manage api-printer.service
    from the GUI without a password prompt.  polkit watches this directory
    via inotify and picks up the new rule immediately.
    """
    path = Path(POLKIT_RULE_PATH)
    log(f"  writing {path}")
    os.makedirs(path.parent, exist_ok=True)
    path.write_text(POLKIT_RULE)
    path.chmod(0o644)


def _step_desktop(install_dir, log):
    # Launcher on PATH — one-line wrapper around python3 + the GUI script.
    launcher_body = (
        "#!/bin/sh\n"
        f"exec python3 {install_dir}/{GUI_SCRIPT_NAME} \"$@\"\n"
    )
    log(f"  writing {LAUNCHER_PATH}")
    Path(LAUNCHER_PATH).write_text(launcher_body)
    Path(LAUNCHER_PATH).chmod(0o755)

    # Desktop entry: application menu + XDG autostart
    src_desktop = BUNDLE_DIR / DESKTOP_ENTRY_NAME
    if not src_desktop.exists():
        raise FileNotFoundError(
            f"Desktop entry not found in installer bundle ({src_desktop})."
        )
    for dst in (APPLICATIONS_DESKTOP_PATH, AUTOSTART_DESKTOP_PATH):
        log(f"  writing {dst}")
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src_desktop, dst)
        Path(dst).chmod(0o644)

    # Refresh the desktop DB so the entry shows up without a logout.
    if shutil.which("update-desktop-database"):
        log("  update-desktop-database /usr/share/applications")
        subprocess.run(
            ["update-desktop-database", "/usr/share/applications"],
            capture_output=True, text=True, env=_system_env(), timeout=30,
        )

def _system_env() -> dict:
    """
    Return a copy of os.environ with PyInstaller's LD_LIBRARY_PATH override
    undone, so that system binaries (systemctl, etc.) link against the
    system's own libcrypto / libsystemd instead of the older copies that
    PyInstaller extracted into /tmp/_MEI… beside our installer.

    PyInstaller preserves the caller's original value in LD_LIBRARY_PATH_ORIG
    when it hijacks LD_LIBRARY_PATH at bootstrap.
    """
    env = os.environ.copy()
    original = env.pop("LD_LIBRARY_PATH_ORIG", None)
    if original is not None:
        env["LD_LIBRARY_PATH"] = original
    else:
        env.pop("LD_LIBRARY_PATH", None)
    return env


def _step_systemd(install_dir, log):
    unit = Path("/etc/systemd/system/api-printer.service")
    log(f"  writing {unit}")
    unit.write_text(
        SERVICE_UNIT.format(
            install_dir=install_dir,
            service_binary=SERVICE_BINARY_NAME,
        )
    )
    env = _system_env()
    for cmd in [
        ["systemctl", "daemon-reload"],
        ["systemctl", "enable",  "api-printer.service"],
        ["systemctl", "restart", "api-printer.service"],
    ]:
        log(f"  {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True, env=env)
        for line in (result.stdout + result.stderr).splitlines():
            if line.strip():
                log(f"    {line}")
        if result.returncode != 0:
            detail = (result.stderr or result.stdout or "").strip() \
                     or f"exit status {result.returncode}"
            raise RuntimeError(
                f"`{' '.join(cmd)}` failed:\n{detail}"
            )


# =============================================================================
# Terminal wizard (headless / SSH)
# =============================================================================

class TerminalInstaller:
    BOLD  = "\033[1m"
    BLUE  = "\033[34m"
    GREEN = "\033[32m"
    RED   = "\033[31m"
    GRAY  = "\033[90m"
    RST   = "\033[0m"

    def run(self):
        self._header()
        self._page_welcome()
        self._page_checks()
        install_dir = self._page_destination()
        self._page_install(install_dir)
        self._page_finish(install_dir)

    def _header(self):
        os.system("clear 2>/dev/null || cls 2>/dev/null || true")
        print(f"{self.BOLD}{self.BLUE}"
              f"╔══════════════════════════════════════════╗\n"
              f"║   API Printer Service {VERSION:<20}║\n"
              f"╚══════════════════════════════════════════╝"
              f"{self.RST}\n")

    def _page_welcome(self):
        print(f"{self.BOLD}Welcome{self.RST}\n")
        print(
            "This wizard will install the API Printer Service on your system.\n\n"
            "The service provides a local REST API on port 5058 that allows\n"
            "POSAwesome to print receipts to CUPS thermal printers.\n\n"
            "What will be installed:\n"
            "  • Service binary →  chosen install directory (self-contained)\n"
            "  • Systemd unit   →  auto-starts on boot\n"
        )
        input("Press Enter to continue… ")
        print()

    def _page_checks(self) -> None:
        print(f"{self.BOLD}System compatibility{self.RST}\n")
        checks = _run_system_checks()
        for c in checks:
            icon = {
                "ok":   f"{self.GREEN}✓{self.RST}",
                "warn": f"{self.BOLD}⚠{self.RST}",
                "fail": f"{self.RED}✗{self.RST}",
            }[c.status]
            line = f"  {icon}  {c.name:<18}"
            if c.message:
                line += f"  {self.GRAY}{c.message}{self.RST}"
            print(line)
        print()

        if _checks_blocking(checks):
            print(f"{self.RED}✗  The system is not suitable for installation.{self.RST}")
            print("   Address the failing check(s) above and run the installer again.\n")
            sys.exit(1)

        if _checks_warnings(checks):
            ans = input("Warnings were reported. Continue anyway? [y/N]: ").strip().lower()
            if ans != "y":
                print("Installation cancelled.")
                sys.exit(0)
            print()

    def _page_destination(self) -> str:
        print(f"{self.BOLD}Install location{self.RST}\n")
        answer = input(
            f"Install directory [{DEFAULT_INSTALL_DIR}]: "
        ).strip()
        install_dir = answer or DEFAULT_INSTALL_DIR
        print(f"\nWill install to: {self.BOLD}{install_dir}{self.RST}")
        confirm = input("Proceed? [Y/n]: ").strip().lower()
        if confirm and confirm != "y":
            print("Installation cancelled.")
            sys.exit(0)
        print()
        return install_dir

    def _page_install(self, install_dir: str):
        print(f"{self.BOLD}Installing…{self.RST}\n")

        def log(msg):
            print(f"  {self.GRAY}{msg}{self.RST}")

        def progress(pct, label):
            bar_width = 40
            filled = int(bar_width * pct / 100)
            bar = "█" * filled + "░" * (bar_width - filled)
            print(f"\r  [{bar}] {pct:>3}%  {label:<40}", end="", flush=True)

        print()
        try:
            run_install_steps(install_dir, log, progress)
            print()
        except Exception as exc:
            print()
            print(f"\n{self.RED}✗  Error: {exc}{self.RST}")
            sys.exit(1)

    def _page_finish(self, install_dir: str):
        print(f"\n{self.BOLD}{self.GREEN}Installation complete ✓{self.RST}\n")
        print(
            f"  Install directory : {install_dir}\n"
            f"  Port              : http://localhost:5058\n"
            f"  Health check      : curl http://localhost:5058/health\n"
            f"  Logs              : {LOG_FILE}\n"
            f"  GUI launcher      : {LAUNCHER_PATH}\n"
            f"                      (also available from the application menu)\n\n"
            f"  systemctl status  api-printer.service\n"
            f"  systemctl stop    api-printer.service\n"
        )


# =============================================================================
# Tkinter GUI wizard
# =============================================================================

DARK_BLUE  = "#1a2a4a"
MID_BLUE   = "#2980b9"
LIGHT_GRAY = "#f0f0f0"
GREEN_OK   = "#27ae60"
AMBER_WARN = "#c9a227"
RED_FAIL   = "#c0392b"


class InstallerApp:
    PAGE_WELCOME     = 0
    PAGE_CHECKS      = 1
    PAGE_DESTINATION = 2
    PAGE_INSTALLING  = 3
    PAGE_FINISH      = 4

    def __init__(self):
        import tkinter as tk
        from tkinter import ttk, filedialog, messagebox
        self._tk         = tk
        self._ttk        = ttk
        self._filedialog = filedialog
        self._messagebox = messagebox

        self.root = tk.Tk()
        self.root.title("API Printer Service — Setup")
        self.root.geometry("620x480")
        self.root.resizable(False, False)
        self.root.configure(bg=LIGHT_GRAY)

        # HiDPI / Wayland scaling: honour GDK_SCALE / QT_SCALE_FACTOR if set,
        # otherwise let Tk auto-detect via its own DPI query.
        try:
            scale = float(os.environ.get("GDK_SCALE") or
                          os.environ.get("QT_SCALE_FACTOR") or 1.0)
            if scale != 1.0:
                self.root.tk.call("tk", "scaling", scale * 1.33)
        except Exception:
            pass

        self.install_dir  = tk.StringVar(value=DEFAULT_INSTALL_DIR)
        self.current_page = -1

        self._build_chrome()
        self._show_page(self.PAGE_WELCOME)

    def run(self):
        self.root.mainloop()

    # ── Chrome ────────────────────────────────────────────────────────────────

    def _build_chrome(self):
        tk = self._tk
        hdr = tk.Frame(self.root, bg=DARK_BLUE, height=90)
        hdr.pack(fill="x")
        hdr.pack_propagate(False)
        tk.Label(hdr, text="⚙  API Printer Service",
                 font=("Helvetica", 20, "bold"),
                 fg="white", bg=DARK_BLUE).pack(side="left", padx=24, pady=24)
        tk.Label(hdr, text=f"Version {VERSION}",
                 font=("Helvetica", 10),
                 fg="#aaccee", bg=DARK_BLUE).place(relx=1.0, rely=1.0,
                                                    anchor="se", x=-16, y=-8)
        tk.Frame(self.root, bg=MID_BLUE, height=3).pack(fill="x")

        self.content = tk.Frame(self.root, bg=LIGHT_GRAY)
        self.content.pack(fill="both", expand=True)

        tk.Frame(self.root, bg="#cccccc", height=1).pack(fill="x")

        bar = tk.Frame(self.root, bg=LIGHT_GRAY, pady=10)
        bar.pack(fill="x")

        self.btn_cancel = tk.Button(bar, text="Cancel", width=10,
                                    command=self._on_cancel,
                                    relief="flat", bg="#e0e0e0", cursor="hand2")
        self.btn_cancel.pack(side="left", padx=16)

        self.btn_back = tk.Button(bar, text="◀  Back", width=10,
                                  command=self._on_back, state="disabled",
                                  relief="flat", bg="#e0e0e0", cursor="hand2")
        self.btn_back.pack(side="right", padx=6)

        self.btn_next = tk.Button(bar, text="Next  ▶", width=12,
                                  command=self._on_next,
                                  relief="flat", bg=MID_BLUE, fg="white",
                                  font=("Helvetica", 10, "bold"), cursor="hand2")
        self.btn_next.pack(side="right", padx=6)

    def _clear(self):
        for w in self.content.winfo_children():
            w.destroy()

    def _show_page(self, page):
        self._clear()
        self.current_page = page
        pages = {
            self.PAGE_WELCOME:     self._render_welcome,
            self.PAGE_CHECKS:      self._render_checks,
            self.PAGE_DESTINATION: self._render_destination,
            self.PAGE_INSTALLING:  self._render_installing,
            self.PAGE_FINISH:      self._render_finish,
        }
        pages[page]()

        self.btn_back.config(
            state="normal" if page in (self.PAGE_CHECKS, self.PAGE_DESTINATION)
            else "disabled")

        if page == self.PAGE_INSTALLING:
            self.btn_next.config(state="disabled", text="Installing…")
            self.btn_back.config(state="disabled")
            self.btn_cancel.config(state="disabled")
        elif page == self.PAGE_FINISH:
            self.btn_next.config(text="Finish", state="normal",
                                 command=self.root.destroy, bg=GREEN_OK)
            self.btn_back.config(state="disabled")
            self.btn_cancel.config(state="disabled")
        elif page == self.PAGE_CHECKS:
            blocked = bool(_checks_blocking(self._checks_list))
            self.btn_next.config(
                text="Next  ▶", command=self._on_next,
                state="disabled" if blocked else "normal",
                bg="#999999" if blocked else MID_BLUE,
            )
        else:
            self.btn_next.config(text="Next  ▶", command=self._on_next,
                                 state="normal", bg=MID_BLUE)

    # ── Pages ─────────────────────────────────────────────────────────────────

    def _render_welcome(self):
        tk = self._tk
        f  = tk.Frame(self.content, bg=LIGHT_GRAY, padx=36, pady=28)
        f.pack(fill="both", expand=True)
        tk.Label(f, text="Welcome to the API Printer Service Installer",
                 font=("Helvetica", 14, "bold"),
                 bg=LIGHT_GRAY, fg=DARK_BLUE).pack(anchor="w")
        tk.Frame(f, bg=MID_BLUE, height=2).pack(fill="x", pady=(8, 18))
        tk.Label(f, justify="left", wraplength=520, bg=LIGHT_GRAY,
                 font=("Helvetica", 10), text=(
            "This wizard will guide you through the installation of the\n"
            "API Printer Service on your Linux system.\n\n"
            "What will be installed:\n"
            "  •  Service binary → chosen install directory (self-contained)\n"
            "  •  Systemd unit   →  auto-starts on boot\n\n"
            "Click  Next  to choose the install location."
        )).pack(anchor="w")

    def _render_checks(self):
        tk = self._tk
        self._checks_list = _run_system_checks()
        blocked = _checks_blocking(self._checks_list)

        f = tk.Frame(self.content, bg=LIGHT_GRAY, padx=36, pady=20)
        f.pack(fill="both", expand=True)

        header = "System Compatibility"
        color  = RED_FAIL if blocked else DARK_BLUE
        tk.Label(f, text=header, font=("Helvetica", 14, "bold"),
                 bg=LIGHT_GRAY, fg=color).pack(anchor="w")
        tk.Frame(f, bg=(RED_FAIL if blocked else MID_BLUE),
                 height=2).pack(fill="x", pady=(8, 14))

        list_frame = tk.Frame(f, bg="white", relief="solid", bd=1)
        list_frame.pack(fill="both", expand=True)
        for c in self._checks_list:
            row = tk.Frame(list_frame, bg="white")
            row.pack(fill="x", padx=10, pady=4)
            icon, fg = {
                "ok":   ("✓", GREEN_OK),
                "warn": ("⚠", AMBER_WARN),
                "fail": ("✗", RED_FAIL),
            }[c.status]
            tk.Label(row, text=icon, fg=fg, bg="white",
                     font=("Helvetica", 12, "bold"), width=2
                     ).pack(side="left")
            tk.Label(row, text=c.name, bg="white",
                     font=("Helvetica", 10, "bold"), width=16, anchor="w"
                     ).pack(side="left")
            if c.message:
                tk.Label(row, text=c.message, bg="white",
                         font=("Helvetica", 9), fg="#444444",
                         wraplength=340, justify="left", anchor="w"
                         ).pack(side="left", fill="x", expand=True)

        footer = tk.Frame(f, bg=LIGHT_GRAY)
        footer.pack(fill="x", pady=(10, 0))
        if blocked:
            tk.Label(footer,
                     text="This system cannot run the service. "
                          "Address the failing check(s) above.",
                     bg=LIGHT_GRAY, fg=RED_FAIL,
                     font=("Helvetica", 9, "bold"),
                     ).pack(side="left")
        tk.Button(footer, text="Re-check", relief="flat", bg="#e0e0e0",
                  cursor="hand2",
                  command=lambda: self._show_page(self.PAGE_CHECKS),
                  ).pack(side="right")

    def _render_destination(self):
        tk = self._tk
        f  = tk.Frame(self.content, bg=LIGHT_GRAY, padx=36, pady=28)
        f.pack(fill="both", expand=True)
        tk.Label(f, text="Choose Install Location",
                 font=("Helvetica", 14, "bold"),
                 bg=LIGHT_GRAY, fg=DARK_BLUE).pack(anchor="w")
        tk.Frame(f, bg=MID_BLUE, height=2).pack(fill="x", pady=(8, 18))
        tk.Label(f, text="Install directory:", bg=LIGHT_GRAY,
                 font=("Helvetica", 10)).pack(anchor="w")
        row = tk.Frame(f, bg=LIGHT_GRAY)
        row.pack(fill="x", pady=(4, 0))
        tk.Entry(row, textvariable=self.install_dir, width=46,
                 font=("Helvetica", 10), relief="solid", bd=1).pack(side="left")
        tk.Button(row, text="Browse…", relief="flat", bg="#e0e0e0",
                  cursor="hand2", command=self._browse).pack(side="left", padx=8)
        tk.Label(f, text="\nRequired disk space: ~80 MB",
                 bg=LIGHT_GRAY, fg="#777777",
                 font=("Helvetica", 9)).pack(anchor="w")

    def _browse(self):
        d = self._filedialog.askdirectory(initialdir=self.install_dir.get())
        if d:
            self.install_dir.set(d)

    def _render_installing(self):
        tk, ttk = self._tk, self._ttk
        f = tk.Frame(self.content, bg=LIGHT_GRAY, padx=36, pady=20)
        f.pack(fill="both", expand=True)
        tk.Label(f, text="Installing…", font=("Helvetica", 14, "bold"),
                 bg=LIGHT_GRAY, fg=DARK_BLUE).pack(anchor="w")
        tk.Frame(f, bg=MID_BLUE, height=2).pack(fill="x", pady=(8, 14))

        self._prog_label = tk.Label(f, text="Preparing…", bg=LIGHT_GRAY,
                                    font=("Helvetica", 10), anchor="w")
        self._prog_label.pack(fill="x")
        self._prog_bar = ttk.Progressbar(f, orient="horizontal",
                                          mode="determinate", length=540)
        self._prog_bar.pack(pady=(6, 12))
        self._log_box = tk.Text(f, height=11, state="disabled",
                                bg="#1e1e1e", fg="#d4d4d4",
                                font=("Courier New", 9), relief="flat")
        self._log_box.pack(fill="both", expand=True)

        threading.Thread(target=self._do_install, daemon=True).start()

    def _log(self, msg):
        self._log_box.config(state="normal")
        self._log_box.insert("end", msg + "\n")
        self._log_box.see("end")
        self._log_box.config(state="disabled")
        self.root.update_idletasks()

    def _set_progress(self, pct, label):
        self._prog_bar["value"] = pct
        self._prog_label.config(text=label)
        self.root.update_idletasks()

    def _do_install(self):
        try:
            run_install_steps(
                self.install_dir.get(),
                log_fn=self._log,
                progress_fn=self._set_progress,
            )
            self.root.after(0, lambda: (
                self.btn_next.config(state="normal", text="Finish",
                                     bg=GREEN_OK,
                                     command=lambda: self._show_page(self.PAGE_FINISH))
            ))
        except Exception as exc:
            self._log(f"\n✗  Error: {exc}")
            self._set_progress(self._prog_bar["value"], "Installation failed.")
            self.root.after(0, lambda: self._messagebox.showerror(
                "Installation Failed",
                f"An error occurred:\n\n{exc}\n\n"
                "Make sure you ran this installer with sudo.",
            ))

    def _render_finish(self):
        tk = self._tk
        f  = tk.Frame(self.content, bg=LIGHT_GRAY, padx=36, pady=28)
        f.pack(fill="both", expand=True)
        tk.Label(f, text="Installation Complete  ✓",
                 font=("Helvetica", 14, "bold"),
                 bg=LIGHT_GRAY, fg=GREEN_OK).pack(anchor="w")
        tk.Frame(f, bg=GREEN_OK, height=2).pack(fill="x", pady=(8, 18))
        tk.Label(f, justify="left", bg=LIGHT_GRAY, font=("Courier New", 9),
                 text=(
            f"  Install directory : {self.install_dir.get()}\n"
            f"  Port              : http://localhost:5058\n"
            f"  Health check      : curl http://localhost:5058/health\n"
            f"  Logs              : {LOG_FILE}\n"
            f"  GUI launcher      : {LAUNCHER_PATH}\n"
            f"                      (also in the application menu)\n\n"
            f"  systemctl status  api-printer.service\n"
            f"  systemctl stop    api-printer.service\n"
        )).pack(anchor="w")

    # ── Navigation ────────────────────────────────────────────────────────────

    def _on_next(self):
        if self.current_page == self.PAGE_WELCOME:
            self._show_page(self.PAGE_CHECKS)
        elif self.current_page == self.PAGE_CHECKS:
            warnings = _checks_warnings(self._checks_list)
            if warnings and not self._messagebox.askyesno(
                "Warnings",
                "Some checks produced warnings:\n\n"
                + "\n".join(f"• {c.name}: {c.message}" for c in warnings)
                + "\n\nContinue anyway?",
            ):
                return
            self._show_page(self.PAGE_DESTINATION)
        elif self.current_page == self.PAGE_DESTINATION:
            if not self.install_dir.get().strip():
                self._messagebox.showwarning("No directory",
                                             "Please enter an install directory.")
                return
            self._show_page(self.PAGE_INSTALLING)

    def _on_back(self):
        if self.current_page == self.PAGE_CHECKS:
            self._show_page(self.PAGE_WELCOME)
        elif self.current_page == self.PAGE_DESTINATION:
            self._show_page(self.PAGE_CHECKS)

    def _on_cancel(self):
        if self._messagebox.askyesno("Cancel", "Cancel installation?"):
            self.root.destroy()


# =============================================================================
# Entry point — GUI if display available, terminal otherwise
# =============================================================================

def _pkexec_relaunch() -> None:
    """
    Re-launch this binary as root via pkexec.

    We do NOT pass --setenv (only supported in pkexec ≥ 0.106; older
    versions treat it as the executable name, producing "Cannot run
    program --setenv").  Instead, _restore_display_from_proc() is called
    once we are root: it walks up the /proc tree and reads DISPLAY /
    WAYLAND_DISPLAY from pkexec's own environ entry, which still holds
    the original user-session variables because pkexec was exec-ed from
    the user's terminal.
    """
    os.execvp("pkexec", ["pkexec", sys.executable] + sys.argv[1:])


if __name__ == "__main__":
    if os.geteuid() != 0:
        # Not root — escalate with pkexec (preserves Wayland/X11 vars)
        # or tell the user to use sudo.
        if shutil.which("pkexec"):
            _pkexec_relaunch()   # replaces the current process
        sys.exit(
            "This installer must be run as root.\n"
            "Run:  sudo ./api-printer-installer-linux"
        )

    if _has_display():
        InstallerApp().run()
    else:
        TerminalInstaller().run()
